{{- if .Values.onedeploy.enabled }}
{{- if and .Values.onedeploy.provisioner.ssh.privateKey (not .Values.onedeploy.provisioner.ssh.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opennebula.fullname" . }}-provisioner-ssh
  labels:
    {{- include "opennebula.labels" . | nindent 4 }}
    app.kubernetes.io/component: host-provisioner
type: Opaque
data:
  id_rsa: {{ .Values.onedeploy.provisioner.ssh.privateKey | b64enc }}
  {{- if .Values.onedeploy.provisioner.ssh.publicKey }}
  id_rsa.pub: {{ .Values.onedeploy.provisioner.ssh.publicKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
